FROM python:3.13-slim

WORKDIR /code

RUN apt-get update && \
    apt-get install -y vim unzip procps && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

