version: "3.9"

services:
  web:
    build: . # 使用當前目錄裡的Dockerfile來建構django Image
    container_name: django_app
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./django:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - backend

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7.4.2
    container_name: redis_cache
    networks:
      - backend

volumes:
  pg_data:

networks:
  backend:
    driver: bridge
