# Generated by Django 5.2.7 on 2025-10-12 13:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(db_column='profile_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(choices=[('BASIC', '一般'), ('VIP', 'VIP'), ('ADMIN', '管理員')], default='BASIC', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userprofile',
                'indexes': [models.Index(fields=['email'], name='userprofile_email_c73093_idx'), models.Index(fields=['type'], name='userprofile_type_e33435_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', Decimal('0.00'))), name='userprofile_balance_non_negative')],
            },
        ),
    ]
