# Generated by Django 5.2.7 on 2025-10-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_product_market_prod_slug_4c00fb_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
